

type CreatedComment {
    commentId: String
    comment: String
  }

type Query {
    getAllComments: [CommentObject]
    getCommentsBySlug(slug: String!): [CommentObject]
  }


type CommentObject {
    commentId: String
    slug: String
    date: String
    name: String
    comment: String
}