type topics{
 topic: String
 content: String
 user: String
 slug: String
}
type Query {
 topics_by_slug: [topics!]
}


 mutation topicCreation {
  createTopics(data: { user: "test",topic:"test",content:"content" }) {
    _id
   user
   topic
   content
  }
 }

query TopicQuery {
  topics_by_slug{
    data {
      _id
      user
      topic 
      content
    }
  }
 }