type topics{
 date: String
 comment: [String]
 user: String
 topic: String
 content: String
 slug: String
}

type Query {  topics_by_slug(slug: String!): topics }

type CreatedComment {
    commentId: String
  }

type Query {
    getAllComments: [CommentObject]
    getCommentsBySlug(slug: String!): [CommentObject]
  }


type CommentObject {
    commentId: String
    slug: String
    date: String
    name: String
    comment: String
}