type comments{
 date: String
 comment: String
 forumID: String
 slug: String
 user: String
}

type Mutation{
    createComment(forumID: ID!): String!
}

type topics{
 date: String
 comment: String
 forumID: String
 slug: String
 user: String
 comments: [comments]!
}
type Query {
 topics_by_id: [topics!]
}