type ai{
 date: String
 topic: String
 content: String
 slug: String
 user: String
 eth_address:String
 upvote: Int
 downvote: Int
}
type Query {
 ai_by_slug(slug:String!):ai
}

# type CreatedAIComment {
#     commentId: String
#     comment: String
#   }

# type Query {
#     # getAllAIComments: [AICommentObject]
#     aiCommentsBySlug(slug: String!): [aiComments]
#   }


# type aiComments {
#     commentId: String
#     slug: String
#     date: String
#     name: String
#     comment: String
# }

# type Query {
#  ai_by_id: [ai!]
# }

