type game{
 date: String
 topic: String
 content: String
 slug: String
 user: String
 eth_address:String
 upvote: Int
 downvote: Int
}
type Query {
 game_by_slug(slug:String!):game
}

# type CreatedGameComment {
#     commentId: String
#     comment: String
#   }

# type Query {
#     getAllGameComments: [GameCommentObject]
#     getGameCommentsBySlug(slug: String!): [GameCommentObject]
#   }


# type GameCommentObject {
#     commentId: String
#     slug: String
#     date: String
#     name: String
#     comment: String
# }

# type Query {
#  game_by_id: [game!]
# }

