type marketplace{
 date: String
 topic: String
 content: String
 slug: String
 user: String
 eth_address:String
 upvote: Int
 downvote: Int
}
type Query {
 marketplace_by_slug(slug:String!):marketplace
}

# type CreatedMarketplaceComment {
#     commentId: String
#     comment: String
#   }

# type Query {
#     getAllMarketplaceComments: [MarketplaceCommentObject]
#     getMarketplaceCommentsBySlug(slug: String!): [MarketplaceCommentObject]
#   }


# type MarketplaceCommentObject {
#     commentId: String
#     slug: String
#     date: String
#     name: String
#     comment: String
# }

# type Query {
#  marketplace_by_id: [marketplace!]
# }

