type users{
 date: String
 name: String
 handle: String
}
# type Query {
#  users_by_slug(slug:String!):users
# }

# type CreatedAIComment {
#     commentId: String
#     comment: String
#   }

# type Query {
#     # getAllAIComments: [AICommentObject]
#     usersCommentsBySlug(slug: String!): [usersComments]
#   }


# type usersComments {
#     commentId: String
#     slug: String
#     date: String
#     name: String
#     comment: String
# }

type Query {
 users_by_id: [users!]
}

